app/posts/models.py
from app import db
from datetime import datetime
from sqlalchemy.orm import backref

# Асоціативна таблиця для зв'язку "багато до багатьох"
post_tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('posts.id'), primary_key=True),
    db.Column('tag_id', db.Integer, db.ForeignKey('tags.id'), primary_key=True)
)

class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    posted = db.Column(db.DateTime, default=datetime.now(), nullable=True)
    is_active = db.Column(db.Boolean, default=True)
    category = db.Column(db.String(50))

    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    author = db.relationship('User', backref=backref('posts', lazy="dynamic"), lazy="joined")

    tags = db.relationship('Tag', secondary=post_tags, back_populates='posts')
    
    def __repr__(self):
        return f"<Post(title={self.title})>"
    
class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    # Зв'язок "багато до багатьох" з постами
    posts = db.relationship('Post', secondary=post_tags, back_populates='tags')

app/posts/__init__.py
from flask import Blueprint

post_bp = Blueprint("posts", __name__, url_prefix="/post",
                    template_folder = "templates/posts",
                    static_folder='static',
                    static_url_path='/static_for_posts')

from . import views

app/posts/views.py
from app.posts.form import PostForm, save_post
from . import post_bp
from flask import render_template, abort, redirect, url_for, flash, session, request
from .models import Post
from app import db
from datetime import datetime
from app.users.models import User

@post_bp.route('/')
def get_posts():
    posts = Post.query.order_by(Post.posted.desc()).all()
    return render_template("posts.html", posts=posts)

@post_bp.route('/<int:id>')
def detail_post(id):
    """Показує деталі поста за його ID."""
    # Отримуємо пост за ID з бази даних
    post = Post.query.get_or_404(id)

    # Відображаємо шаблон із деталями поста
    return render_template("detail_post.html", post=post)

@post_bp.route('/add_post', methods=['GET', 'POST'])
def add_post():
    # Перевіряємо, чи користувач увійшов у систему
    if 'user' not in session:
        flash('Будь ласка, увійдіть, щоб створити пост.', 'error')
        return redirect(url_for('users.login'))

    form = PostForm()

    authors = User.query.all()
    form.author_id.choices = [(author.id, author.username) for author in authors]

    if form.validate_on_submit():
        try:
            save_post(form)

            flash("Пост успішно створено!", "success")
            return redirect(url_for('posts.get_posts'))

        except Exception as e:
            flash(f"Помилка: {str(e)}", "error")
            return redirect(url_for('posts.add_post'))

    return render_template('add_form.html', form=form)

@post_bp.route('/edit_post/<int:post_id>', methods=['GET', 'POST'])
def edit_post(post_id):
    # Отримуємо пост за ID
    post = Post.query.get_or_404(post_id)

    # Ініціалізуємо форму з даними поста
    form = PostForm(obj=post)

    if form.validate_on_submit():
        try:
            # Оновлюємо дані поста
            post.title = form.title.data
            post.content = form.content.data
            post.is_active = True if form.is_active.data == 'true' else False
            post.category = form.category.data
            post.author = form.author.data
            post.posted = form.posted.data

            db.session.commit()
            flash("Пост успішно оновлено!", "success")
            return redirect(url_for('posts.get_posts'))

        except Exception as e:
            flash(f"Помилка: {str(e)}", "error")
            return redirect(url_for('posts.edit_post', post_id=post_id))

    return render_template('edit.html', form=form, post=post)

@post_bp.route('/delete/<int:post_id>', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Пост успішно видалено!', 'success')
    return redirect(url_for('posts.get_posts'))

app/posts/templates/posts/add_form.html
{% extends "base.html" %}
{% from "macros/form_macros.html" import render_field %}

{% block content %}
<h1>Додати новий пост</h1>

<form method="POST" action="{{ url_for('posts.add_post') }}">
    {{ form.hidden_tag() }}

    {{ render_field(form.title) }}
    {{ render_field(form.content) }}
    {{ render_field(form.is_active) }}
    {{ render_field(form.category) }}
    {{ render_field(form.author_id) }}
    {{ render_field(form.posted) }}
    {{ render_field(form.tags) }}

    <div>
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>

{% endblock %}

app/posts/templates/posts/detail_post.html
{% extends 'base.html' %}
{% block title %} POSTS {% endblock %}
{% block content %}
    <h1>Post № {{post.id}} - {{post.title}} </h1>
    <p>{{ post.content }}</p>
    <p><strong>Дата публікації:</strong> {{ post.posted.strftime('%Y-%m-%d %H:%M') }}</p>
    {% for tag in post.tags %}
    <span class="badge bg-primary">{{ tag.name }}</span>
    {% endfor %}
    <br>
    <a href="{{ url_for('posts.get_posts') }}">Повернутись до списку</a>
{% endblock %}

app/posts/templates/posts/edit.html
{% extends "base.html" %}
{% from "macros/form_macros.html" import render_field %}

{% block content %}
<h1>Редагувати пост</h1>

<form method="POST" action="{{ url_for('posts.edit_post', post_id=post.id) }}">
    {{ form.hidden_tag() }}

    {{ render_field(form.title) }}
    {{ render_field(form.content) }}
    {{ render_field(form.is_active) }}
    {{ render_field(form.category) }}
    {{ render_field(form.author) }}
    {{ render_field(form.posted) }}

    <div>
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>

<!-- Виведення повідомлень через Flash -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <ul>
        {% for category, message in messages %}
            <li class="{{ category }}">{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
{% endwith %}
{% endblock %}

app/posts/templates/posts/macros/form_macros.html
{% macro render_field(field) %}
<div class="form-group">
    {{ field.label(class="form-label") }}
    {{ field(class="form-control") }}
    {% if field.errors %}
        <div class="text-danger">
            {% for error in field.errors %}
                <small>{{ error }}</small><br>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endmacro %}

app/posts/templates/posts/posts.html
{% extends 'base.html' %}
{% block title %} POSTS {% endblock %}
{% block content %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('posts.static', filename='css/posts.css') }}">
{% endblock %}

<div class="container">
    <div class="row mt-n5">
        {% for post in posts %}
        <div class="col-md-6 col-lg-4 mt-5 wow fadeInUp" data-wow-delay=".2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
            <div class="blog-grid">
                <div class="blog-grid-img position-relative">
                    <img alt="img" src="{{ post['image_url'] if post['image_url'] else 'https://www.bootdey.com/image/480x480/00FFFF/000000' }}" width="350">
                </div>
                <div class="blog-grid-text p-4"> 
                    <h3 class="h5 mb-3">
                        <a href="{{ url_for('posts.detail_post', id=post['id']) }}">{{ post.title }}</a>
                    </h3>
                    <p class="display-30">{{ post.content }}...</p>
                    <div class="meta meta-style2">
                        <ul>
                            <li><a href="#!"><i class="fas fa-calendar-alt"></i> {{ post.posted.strftime('%Y-%m-%d %H:%M') }}</a></li>
                            <li><a href="#!"><i class="fas fa-user"></i> {{ post.author }}</a></li>
                        </ul>
                    </div>
                    <div class="meta meta-style2">
                        <a href="{{ url_for('posts.edit_post', post_id=post.id) }}">Редагувати</a>
                        <form method="POST" action="{{ url_for('posts.delete_post', post_id=post.id) }}" style="display: inline;">
                            <button type="submit" onclick="return confirm('Ви впевнені, що хочете видалити цей пост?');">Видалити</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}